#!/usr/bin/env python3
"""Generate and sync a Postman collection from Express routes."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}
AUTO_GENERATED_TAG = "AUTO-GENERATED by postman-json"
POSTMAN_SCHEMA = (
    "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
)
POSTMAN_VARIABLE_PATTERN = re.compile(r"\{\{\s*([A-Za-z_$][\w$-]*)\s*\}\}")


@dataclass(frozen=True)
class ImportBinding:
    source_path: Path
    imported_symbol: Optional[str] = None


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def parse_js_string_literal(token: str) -> Optional[str]:
    token = token.strip()
    if len(token) < 2:
        return None
    quote = token[0]
    if quote not in {"'", '"', "`"} or token[-1] != quote:
        return None
    body = token[1:-1]
    if quote == "`" and "${" in body:
        return None
    if quote in {"'", '"'}:
        if quote == "'":
            body = body.replace("\\'", "'")
        if quote == '"':
            body = body.replace('\\"', '"')
        body = body.replace("\\/", "/")
        body = body.replace("\\\\", "\\")
    return body


def find_matching_paren(text: str, open_idx: int) -> Optional[int]:
    depth = 0
    state: Optional[str] = None
    escaped = False
    i = open_idx
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""

        if state == "line_comment":
            if ch == "\n":
                state = None
            i += 1
            continue
        if state == "block_comment":
            if ch == "*" and nxt == "/":
                state = None
                i += 2
                continue
            i += 1
            continue
        if state in {"single", "double", "template"}:
            if escaped:
                escaped = False
                i += 1
                continue
            if ch == "\\":
                escaped = True
                i += 1
                continue
            if (
                (state == "single" and ch == "'")
                or (state == "double" and ch == '"')
                or (state == "template" and ch == "`")
            ):
                state = None
            i += 1
            continue

        if ch == "/" and nxt == "/":
            state = "line_comment"
            i += 2
            continue
        if ch == "/" and nxt == "*":
            state = "block_comment"
            i += 2
            continue
        if ch == "'":
            state = "single"
            i += 1
            continue
        if ch == '"':
            state = "double"
            i += 1
            continue
        if ch == "`":
            state = "template"
            i += 1
            continue
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return None


def split_top_level_commas(expr: str) -> List[str]:
    items: List[str] = []
    start = 0
    paren = 0
    curly = 0
    square = 0
    state: Optional[str] = None
    escaped = False
    i = 0
    while i < len(expr):
        ch = expr[i]
        nxt = expr[i + 1] if i + 1 < len(expr) else ""

        if state == "line_comment":
            if ch == "\n":
                state = None
            i += 1
            continue
        if state == "block_comment":
            if ch == "*" and nxt == "/":
                state = None
                i += 2
                continue
            i += 1
            continue
        if state in {"single", "double", "template"}:
            if escaped:
                escaped = False
                i += 1
                continue
            if ch == "\\":
                escaped = True
                i += 1
                continue
            if (
                (state == "single" and ch == "'")
                or (state == "double" and ch == '"')
                or (state == "template" and ch == "`")
            ):
                state = None
            i += 1
            continue

        if ch == "/" and nxt == "/":
            state = "line_comment"
            i += 2
            continue
        if ch == "/" and nxt == "*":
            state = "block_comment"
            i += 2
            continue
        if ch == "'":
            state = "single"
            i += 1
            continue
        if ch == '"':
            state = "double"
            i += 1
            continue
        if ch == "`":
            state = "template"
            i += 1
            continue
        if ch == "(":
            paren += 1
        elif ch == ")":
            paren -= 1
        elif ch == "{":
            curly += 1
        elif ch == "}":
            curly -= 1
        elif ch == "[":
            square += 1
        elif ch == "]":
            square -= 1
        elif ch == "," and paren == 0 and curly == 0 and square == 0:
            items.append(expr[start:i].strip())
            start = i + 1
        i += 1
    tail = expr[start:].strip()
    if tail:
        items.append(tail)
    return items


def skip_whitespace_and_comments(text: str, idx: int) -> int:
    length = len(text)
    while idx < length:
        if text[idx].isspace():
            idx += 1
            continue
        if text.startswith("//", idx):
            newline = text.find("\n", idx + 2)
            idx = length if newline == -1 else newline + 1
            continue
        if text.startswith("/*", idx):
            end = text.find("*/", idx + 2)
            idx = length if end == -1 else end + 2
            continue
        break
    return idx


def mask_js_comments_and_strings(text: str) -> str:
    """Replace comment/string regions with spaces while preserving indexes."""
    chars = list(text)
    state: Optional[str] = None
    escaped = False
    i = 0
    while i < len(chars):
        ch = chars[i]
        nxt = chars[i + 1] if i + 1 < len(chars) else ""

        if state == "line_comment":
            if ch == "\n":
                state = None
                i += 1
                continue
            chars[i] = " "
            i += 1
            continue
        if state == "block_comment":
            if ch == "*" and nxt == "/":
                chars[i] = " "
                chars[i + 1] = " "
                state = None
                i += 2
                continue
            if ch != "\n":
                chars[i] = " "
            i += 1
            continue
        if state in {"single", "double", "template"}:
            if ch != "\n":
                chars[i] = " "
            if escaped:
                escaped = False
                i += 1
                continue
            if ch == "\\":
                escaped = True
                i += 1
                continue
            if (
                (state == "single" and ch == "'")
                or (state == "double" and ch == '"')
                or (state == "template" and ch == "`")
            ):
                state = None
            i += 1
            continue

        if ch == "/" and nxt == "/":
            chars[i] = " "
            chars[i + 1] = " "
            state = "line_comment"
            i += 2
            continue
        if ch == "/" and nxt == "*":
            chars[i] = " "
            chars[i + 1] = " "
            state = "block_comment"
            i += 2
            continue
        if ch == "'":
            chars[i] = " "
            state = "single"
            i += 1
            continue
        if ch == '"':
            chars[i] = " "
            state = "double"
            i += 1
            continue
        if ch == "`":
            chars[i] = " "
            state = "template"
            i += 1
            continue
        i += 1

    return "".join(chars)


def match_chained_method_call(
    text: str, start_idx: int
) -> Optional[Tuple[str, str, int]]:
    idx = skip_whitespace_and_comments(text, start_idx)
    if idx >= len(text) or text[idx] != ".":
        return None
    idx += 1
    idx = skip_whitespace_and_comments(text, idx)
    name_start = idx
    while idx < len(text) and (text[idx].isalnum() or text[idx] in "_$"):
        idx += 1
    method_name = text[name_start:idx]
    if not method_name:
        return None
    idx = skip_whitespace_and_comments(text, idx)
    if idx >= len(text) or text[idx] != "(":
        return None
    open_idx = idx
    close_idx = find_matching_paren(text, open_idx)
    if close_idx is None:
        return None
    args = text[open_idx + 1 : close_idx]
    return method_name, args, close_idx + 1


def iter_router_route_calls(
    text: str, router_name: str
) -> Iterable[Tuple[str, str, str]]:
    scan_text = mask_js_comments_and_strings(text)
    pattern = re.compile(rf"\b{re.escape(router_name)}\.route\s*\(")
    for match in pattern.finditer(scan_text):
        open_idx = match.end() - 1
        close_idx = find_matching_paren(text, open_idx)
        if close_idx is None:
            continue
        args = text[open_idx + 1 : close_idx]
        parts = split_top_level_commas(args)
        if not parts:
            continue
        route_path = parse_js_string_literal(parts[0])
        if route_path is None:
            continue
        chain_idx = close_idx + 1
        while True:
            chained = match_chained_method_call(text, chain_idx)
            if not chained:
                break
            method_name, method_args, next_idx = chained
            chain_idx = next_idx
            method_lower = method_name.lower()
            if method_lower not in HTTP_METHODS:
                continue
            yield method_lower, method_args, route_path


def iter_object_calls(
    text: str, object_name: str, methods: Optional[Iterable[str]] = None
) -> Iterable[Tuple[str, str, int, int]]:
    allowed = set(m.lower() for m in methods) if methods else None
    scan_text = mask_js_comments_and_strings(text)
    pattern = re.compile(rf"\b{re.escape(object_name)}\.([A-Za-z_$][\w$]*)\s*\(")
    for match in pattern.finditer(scan_text):
        method = match.group(1)
        if allowed is not None and method.lower() not in allowed:
            continue
        open_idx = match.end() - 1
        close_idx = find_matching_paren(text, open_idx)
        if close_idx is None:
            continue
        args = text[open_idx + 1 : close_idx]
        yield method.lower(), args, match.start(), close_idx


def extract_identifier(expr: str) -> Optional[str]:
    expr = expr.strip()
    if not expr:
        return None
    if expr.startswith("..."):
        expr = expr[3:].lstrip()
    match = re.match(r"^([A-Za-z_$][\w$]*)", expr)
    return match.group(1) if match else None


def extract_named_binding_aliases(raw_bindings: str) -> Dict[str, str]:
    aliases: Dict[str, str] = {}
    for raw_binding in split_top_level_commas(raw_bindings):
        binding = raw_binding.strip()
        if not binding or binding.startswith("..."):
            continue
        if "=" in binding:
            binding = binding.split("=", 1)[0].strip()
        original: Optional[str] = None
        alias: Optional[str] = None
        if re.search(r"\bas\b", binding):
            left, right = re.split(r"\bas\b", binding, maxsplit=1)
            original = extract_identifier(left)
            alias = extract_identifier(right)
        elif ":" in binding:
            left, right = binding.split(":", 1)
            original = extract_identifier(left)
            alias = extract_identifier(right)
        else:
            original = extract_identifier(binding)
            alias = original
        if original and alias:
            aliases[alias] = original
    return aliases


def expand_identifier_aliases(source_text: str, base_identifiers: set[str]) -> set[str]:
    aliases = set(base_identifiers)
    assignment_pattern = re.compile(
        r"""(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*([A-Za-z_$][\w$]*)\s*;?"""
    )
    changed = True
    while changed:
        changed = False
        for match in assignment_pattern.finditer(source_text):
            alias, original = match.groups()
            if original in aliases and alias not in aliases:
                aliases.add(alias)
                changed = True
    return aliases


def extract_express_factory_aliases(source_text: str) -> set[str]:
    aliases: set[str] = {"express"}
    esm_pattern = re.compile(
        r"""import\s+([A-Za-z_$][\w$]*)\s+from\s+["']express["']\s*;?"""
    )
    cjs_pattern = re.compile(
        r"""(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*require\(\s*["']express["']\s*\)\s*;?"""
    )
    for match in esm_pattern.finditer(source_text):
        aliases.add(match.group(1))
    for match in cjs_pattern.finditer(source_text):
        aliases.add(match.group(1))
    return aliases


def extract_express_app_identifiers(source_text: str) -> List[str]:
    express_factories = extract_express_factory_aliases(source_text)
    app_identifiers: set[str] = set()
    call_assign_pattern = re.compile(
        r"""(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*([A-Za-z_$][\w$]*)\s*\(\s*\)\s*;?"""
    )
    inline_require_pattern = re.compile(
        r"""(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*require\(\s*["']express["']\s*\)\s*\(\s*\)\s*;?"""
    )

    for match in call_assign_pattern.finditer(source_text):
        app_name, factory_alias = match.groups()
        if factory_alias in express_factories:
            app_identifiers.add(app_name)
    for match in inline_require_pattern.finditer(source_text):
        app_identifiers.add(match.group(1))

    app_identifiers = expand_identifier_aliases(source_text, app_identifiers)
    return sorted(app_identifiers)


def extract_router_identifiers(source_text: str) -> List[str]:
    express_factories = extract_express_factory_aliases(source_text)
    router_factories: set[str] = set()
    router_identifiers: set[str] = set()

    esm_named_pattern = re.compile(
        r"""import\s*\{\s*([^}]+)\s*\}\s*from\s*["']express["']\s*;?"""
    )
    cjs_named_pattern = re.compile(
        r"""(?:const|let|var)\s*\{\s*([^}]+)\s*\}\s*=\s*require\(\s*["']express["']\s*\)\s*;?"""
    )
    member_alias_pattern = re.compile(
        r"""(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*([A-Za-z_$][\w$]*)\.Router\s*;?"""
    )
    require_member_alias_pattern = re.compile(
        r"""(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*require\(\s*["']express["']\s*\)\.Router\s*;?"""
    )
    member_call_pattern = re.compile(
        r"""(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*([A-Za-z_$][\w$]*)\.Router\(\s*[^)]*\)\s*;?"""
    )
    factory_call_pattern = re.compile(
        r"""(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*([A-Za-z_$][\w$]*)\(\s*[^)]*\)\s*;?"""
    )
    require_member_call_pattern = re.compile(
        r"""(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*require\(\s*["']express["']\s*\)\.Router\(\s*[^)]*\)\s*;?"""
    )

    for match in esm_named_pattern.finditer(source_text):
        for alias, original in extract_named_binding_aliases(match.group(1)).items():
            if original == "Router":
                router_factories.add(alias)
    for match in cjs_named_pattern.finditer(source_text):
        for alias, original in extract_named_binding_aliases(match.group(1)).items():
            if original == "Router":
                router_factories.add(alias)
    for match in member_alias_pattern.finditer(source_text):
        alias, source_alias = match.groups()
        if source_alias in express_factories:
            router_factories.add(alias)
    for match in require_member_alias_pattern.finditer(source_text):
        router_factories.add(match.group(1))
    for match in member_call_pattern.finditer(source_text):
        router_name, source_alias = match.groups()
        if source_alias in express_factories:
            router_identifiers.add(router_name)
    for match in factory_call_pattern.finditer(source_text):
        router_name, factory_alias = match.groups()
        if factory_alias in router_factories:
            router_identifiers.add(router_name)
    for match in require_member_call_pattern.finditer(source_text):
        router_identifiers.add(match.group(1))

    router_identifiers = expand_identifier_aliases(source_text, router_identifiers)
    return sorted(router_identifiers)


def unwrap_parenthesized_expr(expr: str) -> str:
    candidate = expr.strip()
    while candidate.startswith("(") and candidate.endswith(")"):
        closing_idx = find_matching_paren(candidate, 0)
        if closing_idx != len(candidate) - 1:
            break
        candidate = candidate[1:-1].strip()
    return candidate


def extract_callback_expressions(expr: str) -> List[str]:
    candidate = unwrap_parenthesized_expr(expr)
    if not candidate:
        return []
    if candidate.startswith("..."):
        candidate = candidate[3:].lstrip()
    if candidate.startswith("[") and candidate.endswith("]"):
        nested_exprs: List[str] = []
        for part in split_top_level_commas(candidate[1:-1]):
            nested_exprs.extend(extract_callback_expressions(part))
        return nested_exprs
    return [candidate]


def extract_identifiers_from_expr(expr: str) -> List[str]:
    identifiers: List[str] = []
    for candidate in extract_callback_expressions(expr):
        identifier = extract_identifier(candidate)
        if identifier and identifier not in identifiers:
            identifiers.append(identifier)
    return identifiers


def is_call_expression(expr: str) -> bool:
    candidate = unwrap_parenthesized_expr(expr)
    if not candidate:
        return False
    idx = candidate.find("(")
    if idx == -1:
        return False

    # Treat chained invocations like factory(opts)() as call expressions too.
    while idx < len(candidate):
        if candidate[idx] != "(":
            return False
        close_idx = find_matching_paren(candidate, idx)
        if close_idx is None:
            return False
        next_idx = skip_whitespace_and_comments(candidate, close_idx + 1)
        if next_idx >= len(candidate):
            return True
        if candidate[next_idx] != "(":
            return False
        idx = next_idx
    return False


def parse_require_source(expr: str) -> Optional[str]:
    candidate = unwrap_parenthesized_expr(expr)
    match = re.match(
        r"""^require\(\s*["']([^"']+)["']\s*\)(?:\.[A-Za-z_$][\w$]*)?$""",
        candidate,
    )
    return match.group(1) if match else None


def infer_exported_identifier(source_text: str) -> Optional[str]:
    export_default_pattern = re.compile(
        r"""export\s+default\s+([A-Za-z_$][\w$]*)\s*;?"""
    )
    module_exports_pattern = re.compile(
        r"""module\.exports\s*=\s*([A-Za-z_$][\w$]*)\s*;?"""
    )
    match = export_default_pattern.search(source_text)
    if match:
        return match.group(1)
    match = module_exports_pattern.search(source_text)
    if match:
        return match.group(1)
    return None


def resolve_module_path(from_file: Path, import_path: str) -> Optional[Path]:
    if not import_path.startswith("."):
        return None
    candidate = (from_file.parent / import_path).resolve()
    if candidate.is_file():
        return candidate
    for suffix in (".js", ".ts"):
        with_suffix = candidate.with_suffix(suffix)
        if with_suffix.is_file():
            return with_suffix
    for index_name in ("index.js", "index.ts"):
        index_file = candidate / index_name
        if index_file.is_file():
            return index_file
    return None


def parse_default_imports(file_path: Path, text: str) -> Dict[str, ImportBinding]:
    imports: Dict[str, ImportBinding] = {}
    esm_default_pattern = re.compile(
        r"""import\s+([A-Za-z_$][\w$]*)\s+from\s+["']([^"']+)["']\s*;?"""
    )
    esm_named_pattern = re.compile(
        r"""import\s*\{\s*([^}]+)\s*\}\s*from\s*["']([^"']+)["']\s*;?"""
    )
    esm_default_named_pattern = re.compile(
        r"""import\s+([A-Za-z_$][\w$]*)\s*,\s*\{\s*([^}]+)\s*\}\s*from\s*["']([^"']+)["']\s*;?"""
    )
    cjs_pattern = re.compile(
        r"""(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*require\(\s*["']([^"']+)["']\s*\)\s*(?:\.([A-Za-z_$][\w$]*))?\s*;?"""
    )
    cjs_destructured_pattern = re.compile(
        r"""(?:const|let|var)\s*\{\s*([^}]+)\s*\}\s*=\s*require\(\s*["']([^"']+)["']\s*\)\s*;?"""
    )

    for match in esm_default_pattern.finditer(text):
        alias = match.group(1)
        source = match.group(2)
        resolved = resolve_module_path(file_path, source)
        if resolved:
            imports[alias] = ImportBinding(source_path=resolved, imported_symbol="default")

    for match in esm_named_pattern.finditer(text):
        raw_bindings = match.group(1)
        source = match.group(2)
        resolved = resolve_module_path(file_path, source)
        if not resolved:
            continue
        for alias, original in extract_named_binding_aliases(raw_bindings).items():
            if alias:
                imports[alias] = ImportBinding(
                    source_path=resolved, imported_symbol=original
                )

    for match in esm_default_named_pattern.finditer(text):
        default_alias = match.group(1)
        raw_bindings = match.group(2)
        source = match.group(3)
        resolved = resolve_module_path(file_path, source)
        if not resolved:
            continue
        imports[default_alias] = ImportBinding(
            source_path=resolved, imported_symbol="default"
        )
        for alias, original in extract_named_binding_aliases(raw_bindings).items():
            if alias:
                imports[alias] = ImportBinding(
                    source_path=resolved, imported_symbol=original
                )

    for match in cjs_pattern.finditer(text):
        alias = match.group(1)
        source = match.group(2)
        member = match.group(3)
        resolved = resolve_module_path(file_path, source)
        if resolved:
            imports[alias] = ImportBinding(source_path=resolved, imported_symbol=member)

    for match in cjs_destructured_pattern.finditer(text):
        raw_bindings = match.group(1)
        source = match.group(2)
        resolved = resolve_module_path(file_path, source)
        if not resolved:
            continue
        for alias, original in extract_named_binding_aliases(raw_bindings).items():
            if alias:
                imports[alias] = ImportBinding(
                    source_path=resolved, imported_symbol=original
                )
    return imports


def extract_body_fields(source_text: str) -> List[str]:
    fields = set(re.findall(r"req\.body(?:\?\.|\.)([A-Za-z_$][\w$]*)", source_text))
    bracket_fields = re.findall(
        r"""req\.body(?:\?\.)?\s*\[\s*["']([A-Za-z_$][\w$]*)["']\s*\]""",
        source_text,
    )
    fields.update(bracket_fields)
    destructured = re.findall(
        r"\{\s*([A-Za-z_$][\w$]*(?:\s*,\s*[A-Za-z_$][\w$]*)*)\s*\}\s*=\s*req\.body",
        source_text,
    )
    for group in destructured:
        for name in group.split(","):
            stripped = name.strip()
            if stripped:
                fields.add(stripped)
    return sorted(fields)


def extract_upload_fields(source_text: str) -> List[str]:
    upload_fields: set[str] = set()
    field_name_pattern = re.compile(
        r"""(?:\bname\b|["']name["'])\s*:\s*(['"])([A-Za-z_$][\w$-]*)\1"""
    )
    for method, args, _start, _end in iter_object_calls(
        source_text, "upload", {"single", "array", "fields"}
    ):
        parts = split_top_level_commas(args)
        if not parts:
            continue
        first_arg = parts[0].strip()
        if method in {"single", "array"}:
            field_name = parse_js_string_literal(first_arg)
            if field_name:
                upload_fields.add(field_name)
            continue
        if method == "fields":
            direct_name = parse_js_string_literal(first_arg)
            if direct_name:
                upload_fields.add(direct_name)
            upload_fields.update(
                match.group(2) for match in field_name_pattern.finditer(first_arg)
            )
    return sorted(upload_fields)


def path_join(prefix: str, suffix: str) -> str:
    left = prefix.strip("/")
    right = suffix.strip("/")
    if not left and not right:
        return "/"
    if not left:
        return f"/{right}" if right else "/"
    if not right:
        return f"/{left}"
    return f"/{left}/{right}"


def to_postman_path(path: str) -> str:
    return re.sub(r":([A-Za-z_$][\w$]*)", r"{{\1}}", path)


def infer_field_example(field_name: str) -> Any:
    lowered = field_name.lower()
    if lowered.endswith("url"):
        return "https://example.com/resource.jpg"
    if lowered.endswith("token"):
        return "replace-with-token"
    if lowered.endswith("id"):
        return "example-id"
    return "sample-value"


def ensure_variable(
    collection: Dict[str, Any],
    key: str,
    default_value: str,
    description: str,
    overwrite: bool = False,
) -> None:
    variables = collection.setdefault("variable", [])
    for variable in variables:
        if variable.get("key") == key:
            if overwrite:
                variable["value"] = default_value
                variable["type"] = "string"
                variable["description"] = description
            return
    variables.append({"key": key, "value": default_value, "type": "string", "description": description})


def get_variable_value(collection: Dict[str, Any], key: str) -> Optional[str]:
    for variable in collection.get("variable", []):
        if variable.get("key") == key:
            value = variable.get("value")
            return value if isinstance(value, str) else None
    return None


def resolve_path_from_root(root: Path, raw_path: str) -> Path:
    path = Path(raw_path)
    if path.is_absolute():
        return path.resolve()
    return (root / path).resolve()


def collect_referenced_variables(item: Any) -> set[str]:
    variables: set[str] = set()
    if isinstance(item, str):
        variables.update(match.group(1) for match in POSTMAN_VARIABLE_PATTERN.finditer(item))
    elif isinstance(item, list):
        for entry in item:
            variables.update(collect_referenced_variables(entry))
    elif isinstance(item, dict):
        for value in item.values():
            variables.update(collect_referenced_variables(value))
    return variables


def infer_variable_metadata(variable_name: str, base_url: str) -> Tuple[str, str]:
    lowered = variable_name.lower()
    if variable_name == "baseUrl":
        return (
            base_url,
            "Base URL for API requests, including protocol and port.",
        )
    if lowered.endswith("token"):
        return (
            "replace-with-token",
            f"Token value for {variable_name} placeholder.",
        )
    if lowered.endswith("url"):
        return (
            "https://example.com",
            f"URL value for {variable_name} placeholder.",
        )
    if lowered.endswith("id"):
        return (
            "example-id",
            f"Identifier value for {variable_name} placeholder.",
        )
    return (
        f"replace-with-{variable_name}",
        f"Value for {variable_name} placeholder used by generated requests.",
    )


def discover_server_file(project_root: Path, explicit_server_file: Optional[str]) -> Optional[Path]:
    if explicit_server_file:
        candidate = resolve_path_from_root(project_root, explicit_server_file)
        return candidate if candidate.exists() else None

    preferred_candidates = [
        "server.js",
        "server.ts",
        "app.js",
        "app.ts",
        "src/server.js",
        "src/server.ts",
        "src/app.js",
        "src/app.ts",
        "backend/server.js",
        "backend/server.ts",
        "backend/app.js",
        "backend/app.ts",
    ]
    for rel in preferred_candidates:
        candidate = (project_root / rel).resolve()
        if candidate.is_file():
            return candidate

    excluded_dirs = {"node_modules", ".git", "dist", "build", "coverage"}
    scanned_candidates: List[Path] = []
    for pattern in ("*.js", "*.ts"):
        rglob_iter = project_root.rglob(pattern)
        while True:
            try:
                candidate = next(rglob_iter)
            except StopIteration:
                break
            except OSError as exc:
                print(
                    f"Warning: skipping inaccessible path while scanning for server file: {exc}",
                    file=sys.stderr,
                )
                continue
            relative_parts = candidate.relative_to(project_root).parts
            if any(part in excluded_dirs for part in relative_parts[:-1]):
                continue
            try:
                text = read_text(candidate)
            except (OSError, UnicodeDecodeError):
                continue
            app_identifiers = extract_express_app_identifiers(text)
            if not app_identifiers:
                continue
            if any(re.search(rf"\b{re.escape(name)}\.use\s*\(", text) for name in app_identifiers):
                scanned_candidates.append(candidate.resolve())

    if not scanned_candidates:
        return None
    return sorted(scanned_candidates, key=lambda path: (len(path.parts), len(str(path))))[0]


def default_output_path(project_root: Path) -> Path:
    project_name = project_root.name.strip() or "api"
    filename = f"{project_name}.postman_collection.json"
    return (project_root / "postman" / filename).resolve()


def default_collection_name(project_root: Path) -> str:
    project_name = project_root.name.strip() or "API"
    words = [word for word in re.split(r"[-_]+", project_name) if word]
    if not words:
        return "API"
    return f"{' '.join(word.capitalize() for word in words)} API"


def extract_mounts(server_path: Path, server_text: str) -> List[Dict[str, Any]]:
    imports = parse_default_imports(server_path, server_text)
    mounts: List[Dict[str, Any]] = []
    seen: set[Tuple[str, Path, str]] = set()
    for app_name in extract_express_app_identifiers(server_text):
        for method, args, _start, _end in iter_object_calls(server_text, app_name, {"use"}):
            if method != "use":
                continue
            parts = split_top_level_commas(args)
            if not parts:
                continue
            mount_path = "/"
            callback_parts = parts
            if len(parts) >= 2:
                parsed_mount_path = parse_js_string_literal(parts[0])
                if parsed_mount_path is not None:
                    mount_path = parsed_mount_path or "/"
                    callback_parts = parts[1:]

            for callback_part in callback_parts:
                for callback_expr in extract_callback_expressions(callback_part):
                    callback_expr = callback_expr.strip()
                    if is_call_expression(callback_expr) and not parse_require_source(callback_expr):
                        continue
                    inline_source = parse_require_source(callback_expr)
                    router_name = None if inline_source else extract_identifier(callback_expr)
                    route_file: Optional[Path] = (
                        imports.get(router_name).source_path
                        if router_name and router_name in imports
                        else None
                    )

                    if not route_file and inline_source:
                        route_file = resolve_module_path(server_path, inline_source)
                        if route_file and not router_name:
                            try:
                                router_name = infer_exported_identifier(read_text(route_file))
                            except (OSError, UnicodeDecodeError):
                                router_name = None
                            if not router_name:
                                router_name = Path(inline_source).stem

                    if not route_file or not router_name:
                        continue

                    key = (mount_path, route_file, router_name)
                    if key in seen:
                        continue
                    seen.add(key)
                    mounts.append(
                        {
                            "router_name": router_name,
                            "mount_path": mount_path,
                            "route_file": route_file,
                        }
                    )
    return mounts


def find_matching_brace(text: str, open_idx: int) -> Optional[int]:
    depth = 0
    state: Optional[str] = None
    escaped = False
    i = open_idx
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""

        if state == "line_comment":
            if ch == "\n":
                state = None
            i += 1
            continue
        if state == "block_comment":
            if ch == "*" and nxt == "/":
                state = None
                i += 2
                continue
            i += 1
            continue
        if state in {"single", "double", "template"}:
            if escaped:
                escaped = False
                i += 1
                continue
            if ch == "\\":
                escaped = True
                i += 1
                continue
            if (
                (state == "single" and ch == "'")
                or (state == "double" and ch == '"')
                or (state == "template" and ch == "`")
            ):
                state = None
            i += 1
            continue

        if ch == "/" and nxt == "/":
            state = "line_comment"
            i += 2
            continue
        if ch == "/" and nxt == "*":
            state = "block_comment"
            i += 2
            continue
        if ch == "'":
            state = "single"
            i += 1
            continue
        if ch == '"':
            state = "double"
            i += 1
            continue
        if ch == "`":
            state = "template"
            i += 1
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return None


def find_statement_end(text: str, start_idx: int) -> int:
    paren = 0
    curly = 0
    square = 0
    state: Optional[str] = None
    escaped = False
    i = start_idx
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""

        if state == "line_comment":
            if ch == "\n":
                state = None
            i += 1
            continue
        if state == "block_comment":
            if ch == "*" and nxt == "/":
                state = None
                i += 2
                continue
            i += 1
            continue
        if state in {"single", "double", "template"}:
            if escaped:
                escaped = False
                i += 1
                continue
            if ch == "\\":
                escaped = True
                i += 1
                continue
            if (
                (state == "single" and ch == "'")
                or (state == "double" and ch == '"')
                or (state == "template" and ch == "`")
            ):
                state = None
            i += 1
            continue

        if ch == "/" and nxt == "/":
            state = "line_comment"
            i += 2
            continue
        if ch == "/" and nxt == "*":
            state = "block_comment"
            i += 2
            continue
        if ch == "'":
            state = "single"
            i += 1
            continue
        if ch == '"':
            state = "double"
            i += 1
            continue
        if ch == "`":
            state = "template"
            i += 1
            continue

        if ch == "(":
            paren += 1
        elif ch == ")":
            paren -= 1
        elif ch == "{":
            curly += 1
        elif ch == "}":
            curly -= 1
        elif ch == "[":
            square += 1
        elif ch == "]":
            square -= 1
        elif ch == ";" and paren == 0 and curly == 0 and square == 0:
            return i + 1
        i += 1
    return len(text)


def collect_exported_local_candidates(source_text: str, export_name: str) -> set[str]:
    candidates = {export_name}

    export_list_pattern = re.compile(r"""export\s*\{\s*([^}]+)\s*\}\s*;?""")
    for match in export_list_pattern.finditer(source_text):
        bindings = extract_named_binding_aliases(match.group(1))
        for alias, original in bindings.items():
            if alias == export_name:
                candidates.add(original)

    module_exports_pattern = re.compile(r"""module\.exports\s*=\s*\{""")
    for match in module_exports_pattern.finditer(source_text):
        open_brace = source_text.find("{", match.start())
        if open_brace == -1:
            continue
        close_brace = find_matching_brace(source_text, open_brace)
        if close_brace is None:
            continue
        for part in split_top_level_commas(source_text[open_brace + 1 : close_brace]):
            entry = part.strip()
            if not entry:
                continue
            if ":" in entry:
                left, right = entry.split(":", 1)
                key = parse_js_string_literal(left.strip()) or extract_identifier(left)
                value_identifier = extract_identifier(right)
                if key == export_name and value_identifier and value_identifier != "async":
                    candidates.add(value_identifier)
            else:
                shorthand = extract_identifier(entry)
                if shorthand == export_name:
                    candidates.add(shorthand)

    return candidates


def collect_scoped_source_for_symbol(source_text: str, export_name: str) -> Optional[str]:
    snippets: List[str] = []
    seen_spans: set[Tuple[int, int]] = set()
    seen_inline_snippets: set[str] = set()

    def append_span(start: int, end: int) -> None:
        if end <= start:
            return
        key = (start, end)
        if key in seen_spans:
            return
        seen_spans.add(key)
        snippets.append(source_text[start:end])

    def append_inline_snippet(snippet: str) -> None:
        normalized = snippet.strip()
        if not normalized or normalized in seen_inline_snippets:
            return
        seen_inline_snippets.add(normalized)
        snippets.append(normalized)

    def assignment_span_end(match_start: int, after_match_idx: int) -> int:
        end = find_statement_end(source_text, match_start)
        if end != len(source_text):
            return end
        # ASI-safe fallback when there is no trailing semicolon.
        open_brace = source_text.find("{", after_match_idx)
        if open_brace != -1:
            close_brace = find_matching_brace(source_text, open_brace)
            if close_brace is not None:
                return close_brace + 1
        return end

    symbols_to_scan: set[str]
    if export_name == "default":
        symbols_to_scan = set()
        for pattern in (
            re.compile(r"""export\s+default\b"""),
            re.compile(r"""module\.exports\s*="""),
            re.compile(r"""(?:module\.)?exports\.default\s*="""),
        ):
            for match in pattern.finditer(source_text):
                end = assignment_span_end(match.start(), match.end())
                append_span(match.start(), end)
                statement = source_text[match.start() : end]
                rhs = None
                export_default_match = re.search(
                    r"""export\s+default\s+(.+?)\s*;?\s*$""",
                    statement,
                    re.DOTALL,
                )
                if export_default_match:
                    rhs = export_default_match.group(1).strip()
                else:
                    assignment_rhs_match = re.search(r"""=\s*(.+?)\s*;?\s*$""", statement, re.DOTALL)
                    if assignment_rhs_match:
                        rhs = assignment_rhs_match.group(1).strip()
                if rhs:
                    identifier = extract_identifier(rhs)
                    if identifier:
                        symbols_to_scan.add(identifier)
    else:
        module_exports_pattern = re.compile(r"""module\.exports\s*=\s*\{""")
        for match in module_exports_pattern.finditer(source_text):
            open_brace = source_text.find("{", match.start())
            if open_brace == -1:
                continue
            close_brace = find_matching_brace(source_text, open_brace)
            if close_brace is None:
                continue
            object_body = source_text[open_brace + 1 : close_brace]
            for part in split_top_level_commas(object_body):
                entry = part.strip()
                if not entry or ":" not in entry:
                    continue
                left, right = entry.split(":", 1)
                key = parse_js_string_literal(left.strip()) or extract_identifier(left)
                if key == export_name:
                    append_inline_snippet(right)
        symbols_to_scan = collect_exported_local_candidates(source_text, export_name)

    for symbol in symbols_to_scan:
        function_pattern = re.compile(
            rf"""(?:export\s+)?(?:async\s+)?function\s+{re.escape(symbol)}\s*\("""
        )
        for match in function_pattern.finditer(source_text):
            param_open = match.end() - 1
            param_close = find_matching_paren(source_text, param_open)
            if param_close is None:
                continue
            open_brace = source_text.find("{", param_close + 1)
            if open_brace == -1:
                continue
            close_brace = find_matching_brace(source_text, open_brace)
            if close_brace is None:
                continue
            append_span(match.start(), close_brace + 1)

        for pattern in (
            re.compile(
                rf"""(?:export\s+)?(?:const|let|var)\s+{re.escape(symbol)}\s*="""
            ),
            re.compile(
                rf"""(?:module\.)?exports\.{re.escape(symbol)}\s*="""
            ),
            re.compile(
                rf"""module\.exports\s*\[\s*["']{re.escape(symbol)}["']\s*\]\s*="""
            ),
        ):
            for match in pattern.finditer(source_text):
                append_span(
                    match.start(),
                    assignment_span_end(match.start(), match.end()),
                )

    return "\n".join(snippets) if snippets else None


def analyze_source_requirements(source_text: str) -> Dict[str, Any]:
    return {
        "body_fields": extract_body_fields(source_text),
        "auth": bool(re.search(r"req\.headers\.authorization", source_text)),
        "needs_file": bool(re.search(r"\breq\.files?\b", source_text)),
        "upload_fields": extract_upload_fields(source_text),
    }


def build_endpoint_from_parts(
    *,
    method: str,
    route_path: str,
    middleware_parts: List[str],
    handler_source: str,
    mount_path: str,
    route_imports: Dict[str, ImportBinding],
    requirement_cache: Dict[Tuple[Path, Optional[str]], Dict[str, Any]],
    route_relative: str,
) -> Dict[str, Any]:
    middleware_names: List[str] = []
    for middleware_part in middleware_parts:
        for middleware_name in extract_identifiers_from_expr(middleware_part):
            if middleware_name not in middleware_names:
                middleware_names.append(middleware_name)
    route_scope_source = "\n".join([*middleware_parts, handler_source])

    body_fields = set(extract_body_fields(route_scope_source))
    upload_fields = set(extract_upload_fields(route_scope_source))
    auth_required = False
    needs_file = bool(re.search(r"\breq\.files?\b", route_scope_source))

    for middleware in middleware_names:
        lowered = middleware.lower()
        if "auth" in lowered:
            auth_required = True
        if "upload" in lowered:
            needs_file = True

        binding = route_imports.get(middleware)
        if not binding:
            continue
        source_path = binding.source_path
        imported_symbol = binding.imported_symbol
        if not source_path.exists():
            continue

        cache_key = (source_path, imported_symbol)
        if cache_key not in requirement_cache:
            try:
                source_text = read_text(source_path)
            except (OSError, UnicodeDecodeError) as exc:
                print(
                    f"Warning: cannot read middleware source {source_path}: {exc}",
                    file=sys.stderr,
                )
                continue

            if imported_symbol:
                scoped_source = collect_scoped_source_for_symbol(
                    source_text, imported_symbol
                )
                if scoped_source:
                    requirement_cache[cache_key] = analyze_source_requirements(
                        scoped_source
                    )
                else:
                    # If scoped extraction misses a valid export shape,
                    # fall back to file-level inference instead of dropping signals.
                    requirement_cache[cache_key] = analyze_source_requirements(source_text)
            else:
                requirement_cache[cache_key] = analyze_source_requirements(source_text)

        requirement = requirement_cache[cache_key]
        body_fields.update(requirement["body_fields"])
        upload_fields.update(requirement["upload_fields"])
        auth_required = auth_required or requirement["auth"]
        needs_file = needs_file or requirement["needs_file"]

    full_path = path_join(mount_path, route_path)
    return {
        "method": method.upper(),
        "path": full_path,
        "path_postman": to_postman_path(full_path),
        "route_file_relative": route_relative,
        "middleware_names": middleware_names,
        "body_fields": sorted(body_fields),
        "upload_fields": sorted(upload_fields),
        "needs_file": needs_file or bool(upload_fields),
        "auth_required": auth_required,
    }


def parse_route_endpoints(
    route_file: Path,
    mount_path: str,
    project_root: Path,
    requirement_cache: Dict[Tuple[Path, Optional[str]], Dict[str, Any]],
    mounted_router_name: Optional[str] = None,
) -> List[Dict[str, Any]]:
    try:
        route_text = read_text(route_file)
    except (OSError, UnicodeDecodeError) as exc:
        print(f"Warning: cannot read route file {route_file}: {exc}", file=sys.stderr)
        return []
    route_imports = parse_default_imports(route_file, route_text)
    try:
        route_relative = str(route_file.relative_to(project_root))
    except ValueError:
        route_relative = route_file.name
    endpoints: List[Dict[str, Any]] = []

    router_names: List[str]
    mounted_router_identifier = extract_identifier(mounted_router_name or "")
    if mounted_router_identifier:
        mounted_aliases = sorted(
            expand_identifier_aliases(route_text, {mounted_router_identifier})
        )
        has_endpoint_calls = False
        for alias in mounted_aliases:
            if any(iter_object_calls(route_text, alias, HTTP_METHODS)) or any(
                iter_router_route_calls(route_text, alias)
            ):
                has_endpoint_calls = True
                break

        # Common Express pattern: server imports route module as `usersRouter`,
        # but the module itself defines routes on `router`.
        if has_endpoint_calls:
            router_names = mounted_aliases
        else:
            router_names = extract_router_identifiers(route_text)
    else:
        router_names = extract_router_identifiers(route_text)
    if not router_names:
        print(
            f"Warning: no router identifiers detected in {route_file}",
            file=sys.stderr,
        )
        return []

    for router_name in router_names:
        for method, args, _start, _end in iter_object_calls(route_text, router_name, HTTP_METHODS):
            parts = split_top_level_commas(args)
            if len(parts) < 2:
                continue

            route_path = parse_js_string_literal(parts[0])
            if route_path is None:
                continue

            middleware_parts = parts[1:-1]
            handler_source = parts[-1]
            endpoints.append(
                build_endpoint_from_parts(
                    method=method,
                    route_path=route_path,
                    middleware_parts=middleware_parts,
                    handler_source=handler_source,
                    mount_path=mount_path,
                    route_imports=route_imports,
                    requirement_cache=requirement_cache,
                    route_relative=route_relative,
                )
            )
        for method, method_args, route_path in iter_router_route_calls(route_text, router_name):
            handler_parts = split_top_level_commas(method_args)
            if not handler_parts:
                continue

            middleware_parts = handler_parts[:-1]
            handler_source = handler_parts[-1]
            endpoints.append(
                build_endpoint_from_parts(
                    method=method,
                    route_path=route_path,
                    middleware_parts=middleware_parts,
                    handler_source=handler_source,
                    mount_path=mount_path,
                    route_imports=route_imports,
                    requirement_cache=requirement_cache,
                    route_relative=route_relative,
                )
            )

    return endpoints


def build_request(endpoint: Dict[str, Any]) -> Dict[str, Any]:
    path_segments = [segment for segment in endpoint["path_postman"].split("/") if segment]
    request: Dict[str, Any] = {
        "method": endpoint["method"],
        "url": {
            "raw": f"{{{{baseUrl}}}}{endpoint['path_postman']}",
            "host": ["{{baseUrl}}"],
            "path": path_segments,
        },
        "description": (
            f"{AUTO_GENERATED_TAG}\n"
            f"Endpoint: {endpoint['method']} {endpoint['path']}\n"
            f"Source: {endpoint['route_file_relative']}"
        ),
    }
    headers: List[Dict[str, str]] = []
    body_fields = set(endpoint["body_fields"])
    upload_fields = set(endpoint["upload_fields"])

    if endpoint["auth_required"]:
        request["auth"] = {
            "type": "bearer",
            "bearer": [{"key": "token", "value": "{{token}}", "type": "string"}],
        }

    if endpoint["needs_file"] or upload_fields:
        if not upload_fields:
            upload_fields.add("file")
        form_data: List[Dict[str, Any]] = []
        for upload_field in sorted(upload_fields):
            form_data.append(
                {"key": upload_field, "type": "file", "src": "", "description": "Attach a local file"}
            )
            body_fields.discard(upload_field)
        for body_field in sorted(body_fields):
            form_data.append(
                {
                    "key": body_field,
                    "value": str(infer_field_example(body_field)),
                    "type": "text",
                }
            )
        request["body"] = {"mode": "formdata", "formdata": form_data}
    elif body_fields:
        payload = {field: infer_field_example(field) for field in sorted(body_fields)}
        headers.append({"key": "Content-Type", "value": "application/json"})
        request["body"] = {
            "mode": "raw",
            "raw": json.dumps(payload, indent=2),
            "options": {"raw": {"language": "json"}},
        }

    if headers:
        request["header"] = headers
    return request


def ensure_folder(parent_items: List[Dict[str, Any]], folder_name: str) -> Dict[str, Any]:
    for item in parent_items:
        if item.get("name") == folder_name and isinstance(item.get("item"), list):
            return item
    new_folder = {"name": folder_name, "item": []}
    parent_items.append(new_folder)
    return new_folder


def build_generated_tree(endpoints: Sequence[Dict[str, Any]], root_name: str) -> Dict[str, Any]:
    root = {"name": root_name, "description": AUTO_GENERATED_TAG, "item": []}
    sorted_endpoints = sorted(
        endpoints, key=lambda entry: (entry["route_file_relative"], entry["path"], entry["method"])
    )
    for endpoint in sorted_endpoints:
        normalized_relative = str(endpoint["route_file_relative"]).replace("\\", "/")
        route_parts = Path(normalized_relative).with_suffix("").parts
        current = root
        for part in route_parts:
            current = ensure_folder(current["item"], part)
        current["item"].append(
            {
                "name": f"{endpoint['method']} {endpoint['path']}",
                "request": build_request(endpoint),
                "response": [],
            }
        )
    return root


def default_collection(collection_name: str) -> Dict[str, Any]:
    return {
        "info": {
            "name": collection_name,
            "schema": POSTMAN_SCHEMA,
        },
        "item": [],
        "variable": [],
    }


def load_collection(path: Path, collection_name: str) -> Dict[str, Any]:
    if not path.exists():
        return default_collection(collection_name)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Failed to parse existing collection JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError("Existing collection JSON is not an object.")
    data.setdefault("info", {})
    data.setdefault("item", [])
    data.setdefault("variable", [])
    existing_schema = data.get("info", {}).get("schema", "")
    if existing_schema and existing_schema != POSTMAN_SCHEMA:
        print(
            f"Warning: existing collection uses schema {existing_schema!r}; upgrading to {POSTMAN_SCHEMA!r}. Verify manually.",
            file=sys.stderr,
        )
    if "name" not in data["info"]:
        data["info"]["name"] = collection_name
    if "schema" not in data["info"]:
        data["info"]["schema"] = POSTMAN_SCHEMA
    return data


def replace_generated_root(
    collection: Dict[str, Any], generated_root: Dict[str, Any], root_name: str
) -> None:
    items = collection.setdefault("item", [])
    kept: List[Dict[str, Any]] = []
    for item in items:
        if (
            item.get("name") == root_name
            and isinstance(item.get("item"), list)
            and AUTO_GENERATED_TAG in str(item.get("description", ""))
        ):
            continue
        kept.append(item)
    kept.append(generated_root)
    collection["item"] = kept


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate/update Postman collection JSON from Express routes."
    )
    parser.add_argument(
        "--project-root",
        "--backend-root",
        dest="project_root",
        default=".",
        help="Project root directory for path resolution",
    )
    parser.add_argument(
        "--server-file",
        default=None,
        help="Server entry file. When omitted, a best-effort discovery is used.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Path for the Postman collection JSON. Defaults to ./postman/<project>.postman_collection.json",
    )
    parser.add_argument(
        "--collection-name",
        default=None,
        help="Postman collection name. Defaults to <Project Name> API",
    )
    parser.add_argument(
        "--base-url",
        default=None,
        help="Default baseUrl variable. When omitted, existing collection value is preserved.",
    )
    parser.add_argument(
        "--generated-root-name",
        default="source",
        help="Top-level generated folder name inside collection",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str]) -> int:
    args = parse_args(argv)

    project_root = Path(args.project_root).resolve()
    server_file = discover_server_file(project_root, args.server_file)
    output_file = (
        resolve_path_from_root(project_root, args.output)
        if args.output
        else default_output_path(project_root)
    )
    collection_name = args.collection_name or default_collection_name(project_root)

    if not project_root.exists():
        print(f"Error: project root not found: {project_root}", file=sys.stderr)
        return 1
    if not server_file:
        print(
            "Error: unable to discover server file. Pass --server-file explicitly.",
            file=sys.stderr,
        )
        return 1
    if not server_file.exists():
        print(f"Error: server file not found: {server_file}", file=sys.stderr)
        return 1

    server_text = read_text(server_file)
    mounts = extract_mounts(server_file, server_text)
    if not mounts:
        print(
            "Error: no mounted routers discovered from <expressInstance>.use(...) in server file.",
            file=sys.stderr,
        )
        return 1

    requirement_cache: Dict[Tuple[Path, Optional[str]], Dict[str, Any]] = {}
    endpoints: List[Dict[str, Any]] = []
    for mount in mounts:
        route_file = mount["route_file"]
        if not route_file.exists():
            print(f"Warning: route file not found: {route_file}", file=sys.stderr)
            continue
        file_endpoints = parse_route_endpoints(
            route_file=route_file,
            mount_path=mount["mount_path"],
            project_root=project_root,
            requirement_cache=requirement_cache,
            mounted_router_name=mount.get("router_name"),
        )
        if not file_endpoints:
            print(
                f"Warning: no endpoints found in {route_file} (mounted at '{mount['mount_path']}'). Check router variable names.",
                file=sys.stderr,
            )
        endpoints.extend(file_endpoints)

    seen_endpoints: set[Tuple[str, str]] = set()
    deduped_endpoints: List[Dict[str, Any]] = []
    for endpoint in endpoints:
        key = (endpoint["method"], endpoint["path"])
        if key in seen_endpoints:
            print(
                (
                    "Warning: duplicate endpoint definition ignored: "
                    f"{endpoint['method']} {endpoint['path']} "
                    f"(source: {endpoint['route_file_relative']})"
                ),
                file=sys.stderr,
            )
            continue
        seen_endpoints.add(key)
        deduped_endpoints.append(endpoint)
    endpoints = deduped_endpoints

    if not endpoints:
        print("Error: no router endpoints discovered.", file=sys.stderr)
        return 1

    collection = load_collection(output_file, collection_name)
    if args.collection_name:
        collection["info"]["name"] = args.collection_name
    else:
        collection["info"].setdefault("name", collection_name)
    collection["info"]["schema"] = POSTMAN_SCHEMA

    base_url_value = args.base_url
    if base_url_value is None:
        base_url_value = get_variable_value(collection, "baseUrl") or "http://localhost:3000"

    ensure_variable(
        collection,
        "baseUrl",
        base_url_value,
        "Base URL for API requests, including protocol and port.",
        overwrite=args.base_url is not None,
    )

    generated_root = build_generated_tree(endpoints, args.generated_root_name)
    replace_generated_root(collection, generated_root, args.generated_root_name)
    referenced_variables = collect_referenced_variables(generated_root)
    for variable_name in sorted(referenced_variables):
        default_value, description = infer_variable_metadata(variable_name, base_url_value)
        ensure_variable(collection, variable_name, default_value, description)

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(json.dumps(collection, indent=2) + "\n", encoding="utf-8")

    print(f"Synced Postman collection: {output_file}")
    print(f"Discovered endpoints: {len(endpoints)}")
    print(f"Generated root folder: {args.generated_root_name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
