#!/usr/bin/env python3
"""Generate and sync a Postman collection from Express routes."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

HTTP_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}
AUTO_GENERATED_TAG = "AUTO-GENERATED by postman-json"
POSTMAN_SCHEMA = (
    "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def parse_js_string_literal(token: str) -> Optional[str]:
    token = token.strip()
    if len(token) < 2:
        return None
    quote = token[0]
    if quote not in {"'", '"', "`"} or token[-1] != quote:
        return None
    body = token[1:-1]
    if quote == "`" and "${" in body:
        return None
    return body


def find_matching_paren(text: str, open_idx: int) -> Optional[int]:
    depth = 0
    state: Optional[str] = None
    escaped = False
    i = open_idx
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""

        if state == "line_comment":
            if ch == "\n":
                state = None
            i += 1
            continue
        if state == "block_comment":
            if ch == "*" and nxt == "/":
                state = None
                i += 2
                continue
            i += 1
            continue
        if state in {"single", "double", "template"}:
            if escaped:
                escaped = False
                i += 1
                continue
            if ch == "\\":
                escaped = True
                i += 1
                continue
            if (
                (state == "single" and ch == "'")
                or (state == "double" and ch == '"')
                or (state == "template" and ch == "`")
            ):
                state = None
            i += 1
            continue

        if ch == "/" and nxt == "/":
            state = "line_comment"
            i += 2
            continue
        if ch == "/" and nxt == "*":
            state = "block_comment"
            i += 2
            continue
        if ch == "'":
            state = "single"
            i += 1
            continue
        if ch == '"':
            state = "double"
            i += 1
            continue
        if ch == "`":
            state = "template"
            i += 1
            continue
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return None


def split_top_level_commas(expr: str) -> List[str]:
    items: List[str] = []
    start = 0
    paren = 0
    curly = 0
    square = 0
    state: Optional[str] = None
    escaped = False
    i = 0
    while i < len(expr):
        ch = expr[i]
        nxt = expr[i + 1] if i + 1 < len(expr) else ""

        if state == "line_comment":
            if ch == "\n":
                state = None
            i += 1
            continue
        if state == "block_comment":
            if ch == "*" and nxt == "/":
                state = None
                i += 2
                continue
            i += 1
            continue
        if state in {"single", "double", "template"}:
            if escaped:
                escaped = False
                i += 1
                continue
            if ch == "\\":
                escaped = True
                i += 1
                continue
            if (
                (state == "single" and ch == "'")
                or (state == "double" and ch == '"')
                or (state == "template" and ch == "`")
            ):
                state = None
            i += 1
            continue

        if ch == "/" and nxt == "/":
            state = "line_comment"
            i += 2
            continue
        if ch == "/" and nxt == "*":
            state = "block_comment"
            i += 2
            continue
        if ch == "'":
            state = "single"
            i += 1
            continue
        if ch == '"':
            state = "double"
            i += 1
            continue
        if ch == "`":
            state = "template"
            i += 1
            continue
        if ch == "(":
            paren += 1
        elif ch == ")":
            paren -= 1
        elif ch == "{":
            curly += 1
        elif ch == "}":
            curly -= 1
        elif ch == "[":
            square += 1
        elif ch == "]":
            square -= 1
        elif ch == "," and paren == 0 and curly == 0 and square == 0:
            items.append(expr[start:i].strip())
            start = i + 1
        i += 1
    tail = expr[start:].strip()
    if tail:
        items.append(tail)
    return items


def iter_object_calls(
    text: str, object_name: str, methods: Optional[Iterable[str]] = None
) -> Iterable[Tuple[str, str, int, int]]:
    allowed = set(m.lower() for m in methods) if methods else None
    pattern = re.compile(rf"\b{re.escape(object_name)}\.([A-Za-z_$][\w$]*)\s*\(")
    for match in pattern.finditer(text):
        method = match.group(1)
        if allowed is not None and method.lower() not in allowed:
            continue
        open_idx = match.end() - 1
        close_idx = find_matching_paren(text, open_idx)
        if close_idx is None:
            continue
        args = text[open_idx + 1 : close_idx]
        yield method.lower(), args, match.start(), close_idx


def extract_identifier(expr: str) -> Optional[str]:
    expr = expr.strip()
    if not expr:
        return None
    if expr.startswith("..."):
        expr = expr[3:].lstrip()
    match = re.match(r"^([A-Za-z_$][\w$]*)", expr)
    return match.group(1) if match else None


def resolve_module_path(from_file: Path, import_path: str) -> Optional[Path]:
    if not import_path.startswith("."):
        return None
    candidate = (from_file.parent / import_path).resolve()
    if candidate.is_file():
        return candidate
    with_js = candidate.with_suffix(".js")
    if with_js.is_file():
        return with_js
    index_js = candidate / "index.js"
    if index_js.is_file():
        return index_js
    return None


def parse_default_imports(file_path: Path, text: str) -> Dict[str, Path]:
    imports: Dict[str, Path] = {}
    esm_pattern = re.compile(
        r"""import\s+([A-Za-z_$][\w$]*)\s+from\s+["']([^"']+)["']\s*;?"""
    )
    cjs_pattern = re.compile(
        r"""(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*require\(\s*["']([^"']+)["']\s*\)\s*(?:\.[A-Za-z_$][\w$]*)?\s*;?"""
    )
    cjs_destructured_pattern = re.compile(
        r"""(?:const|let|var)\s*\{\s*([^}]+)\s*\}\s*=\s*require\(\s*["']([^"']+)["']\s*\)\s*;?"""
    )

    for match in esm_pattern.finditer(text):
        alias = match.group(1)
        source = match.group(2)
        resolved = resolve_module_path(file_path, source)
        if resolved:
            imports[alias] = resolved

    for match in cjs_pattern.finditer(text):
        alias = match.group(1)
        source = match.group(2)
        resolved = resolve_module_path(file_path, source)
        if resolved:
            imports[alias] = resolved

    for match in cjs_destructured_pattern.finditer(text):
        raw_bindings = match.group(1)
        source = match.group(2)
        resolved = resolve_module_path(file_path, source)
        if not resolved:
            continue
        for raw_binding in split_top_level_commas(raw_bindings):
            binding = raw_binding.strip()
            if not binding or binding.startswith("..."):
                continue
            if ":" in binding:
                binding = binding.split(":", 1)[1].strip()
            if "=" in binding:
                binding = binding.split("=", 1)[0].strip()
            alias = extract_identifier(binding)
            if alias:
                imports[alias] = resolved
    return imports


def extract_body_fields(source_text: str) -> List[str]:
    fields = set(re.findall(r"req\.body(?:\?\.|\.)([A-Za-z_$][\w$]*)", source_text))
    destructured = re.findall(
        r"\{\s*([A-Za-z_$][\w$]*(?:\s*,\s*[A-Za-z_$][\w$]*)*)\s*\}\s*=\s*req\.body",
        source_text,
    )
    for group in destructured:
        for name in group.split(","):
            stripped = name.strip()
            if stripped:
                fields.add(stripped)
    return sorted(fields)


def extract_upload_fields(source_text: str) -> List[str]:
    return sorted(
        set(
            re.findall(
                r"upload\.(?:single|array|fields)\(\s*['\"]([A-Za-z_$][\w$-]*)['\"]",
                source_text,
            )
        )
    )


def path_join(prefix: str, suffix: str) -> str:
    left = prefix.strip("/")
    right = suffix.strip("/")
    if not left and not right:
        return "/"
    if not left:
        return f"/{right}" if right else "/"
    if not right:
        return f"/{left}"
    return f"/{left}/{right}"


def to_postman_path(path: str) -> str:
    return re.sub(r":([A-Za-z_$][\w$]*)", r"{{\1}}", path)


def infer_field_example(field_name: str) -> Any:
    lowered = field_name.lower()
    if lowered.endswith("url"):
        return "https://example.com/resource.jpg"
    if lowered == "turnstiletoken":
        return "{{turnstileToken}}"
    if lowered.endswith("token"):
        return "replace-with-token"
    if lowered.endswith("id"):
        return "example-id"
    return "sample-value"


def ensure_variable(
    collection: Dict[str, Any], key: str, default_value: str, description: str
) -> None:
    variables = collection.setdefault("variable", [])
    for variable in variables:
        if variable.get("key") == key:
            return
    variables.append({"key": key, "value": default_value, "type": "string", "description": description})


def resolve_path_from_root(root: Path, raw_path: str) -> Path:
    path = Path(raw_path)
    if path.is_absolute():
        return path.resolve()
    return (root / path).resolve()


def discover_server_file(project_root: Path, explicit_server_file: Optional[str]) -> Optional[Path]:
    if explicit_server_file:
        candidate = resolve_path_from_root(project_root, explicit_server_file)
        return candidate if candidate.exists() else None

    preferred_candidates = [
        "server.js",
        "app.js",
        "src/server.js",
        "src/app.js",
        "backend/server.js",
        "backend/app.js",
    ]
    for rel in preferred_candidates:
        candidate = (project_root / rel).resolve()
        if candidate.is_file():
            return candidate

    excluded_dirs = {"node_modules", ".git", "dist", "build", "coverage", "skills"}
    scanned_candidates: List[Path] = []
    for candidate in project_root.rglob("*.js"):
        if any(part in excluded_dirs for part in candidate.parts):
            continue
        try:
            text = read_text(candidate)
        except UnicodeDecodeError:
            continue
        if "app.use(" in text and "express" in text:
            scanned_candidates.append(candidate.resolve())

    if not scanned_candidates:
        return None
    return sorted(scanned_candidates, key=lambda path: (len(path.parts), len(str(path))))[0]


def default_output_path(project_root: Path) -> Path:
    project_name = project_root.name.strip() or "api"
    filename = f"{project_name}.postman_collection.json"
    return (project_root / "postman" / filename).resolve()


def default_collection_name(project_root: Path) -> str:
    project_name = project_root.name.strip() or "API"
    words = [word for word in re.split(r"[-_]+", project_name) if word]
    if not words:
        return "API"
    return f"{' '.join(word.capitalize() for word in words)} API"


def extract_mounts(server_path: Path, server_text: str) -> List[Dict[str, Any]]:
    imports = parse_default_imports(server_path, server_text)
    mounts: List[Dict[str, Any]] = []
    for method, args, _start, _end in iter_object_calls(server_text, "app", {"use"}):
        if method != "use":
            continue
        parts = split_top_level_commas(args)
        if len(parts) < 2:
            continue
        mount_path = parse_js_string_literal(parts[0])
        if not mount_path:
            continue
        router_name = extract_identifier(parts[-1])
        if not router_name:
            continue
        route_file = imports.get(router_name)
        if not route_file:
            continue
        mounts.append(
            {
                "router_name": router_name,
                "mount_path": mount_path,
                "route_file": route_file,
            }
        )
    return mounts


def analyze_source_requirements(source_text: str) -> Dict[str, Any]:
    return {
        "body_fields": extract_body_fields(source_text),
        "auth": bool(re.search(r"req\.headers\.authorization", source_text)),
        "needs_file": bool(re.search(r"\breq\.files?\b", source_text)),
        "upload_fields": extract_upload_fields(source_text),
    }


def parse_route_endpoints(
    route_file: Path,
    mount_path: str,
    project_root: Path,
    requirement_cache: Dict[Path, Dict[str, Any]],
) -> List[Dict[str, Any]]:
    route_text = read_text(route_file)
    route_imports = parse_default_imports(route_file, route_text)
    try:
        route_relative = str(route_file.relative_to(project_root))
    except ValueError:
        route_relative = route_file.name
    endpoints: List[Dict[str, Any]] = []

    for method, args, _start, _end in iter_object_calls(route_text, "router", HTTP_METHODS):
        parts = split_top_level_commas(args)
        if len(parts) < 2:
            continue

        route_path = parse_js_string_literal(parts[0])
        if route_path is None:
            continue

        middleware_parts = parts[1:-1]
        handler_source = parts[-1]
        middleware_names = [name for name in (extract_identifier(p) for p in middleware_parts) if name]
        route_scope_source = "\n".join([*middleware_parts, handler_source])

        body_fields = set(extract_body_fields(handler_source))
        upload_fields = set(extract_upload_fields(route_scope_source))
        auth_required = False
        needs_file = bool(re.search(r"\breq\.files?\b", handler_source))

        for middleware in middleware_names:
            lowered = middleware.lower()
            if "auth" in lowered:
                auth_required = True
            if "upload" in lowered:
                needs_file = True
            if "turnstile" in lowered:
                body_fields.add("turnstileToken")

            source_path = route_imports.get(middleware)
            if not source_path or not source_path.exists():
                continue

            if source_path not in requirement_cache:
                requirement_cache[source_path] = analyze_source_requirements(
                    read_text(source_path)
                )
            requirement = requirement_cache[source_path]
            body_fields.update(requirement["body_fields"])
            upload_fields.update(requirement["upload_fields"])
            auth_required = auth_required or requirement["auth"]
            needs_file = needs_file or requirement["needs_file"]

        full_path = path_join(mount_path, route_path)
        endpoints.append(
            {
                "method": method.upper(),
                "path": full_path,
                "path_postman": to_postman_path(full_path),
                "route_file_relative": route_relative,
                "middleware_names": middleware_names,
                "body_fields": sorted(body_fields),
                "upload_fields": sorted(upload_fields),
                "needs_file": needs_file or bool(upload_fields),
                "auth_required": auth_required,
            }
        )

    return endpoints


def build_request(endpoint: Dict[str, Any]) -> Dict[str, Any]:
    request: Dict[str, Any] = {
        "method": endpoint["method"],
        "url": f"{{{{baseUrl}}}}{endpoint['path_postman']}",
        "description": (
            f"{AUTO_GENERATED_TAG}\n"
            f"Endpoint: {endpoint['method']} {endpoint['path']}\n"
            f"Source: {endpoint['route_file_relative']}"
        ),
    }
    headers: List[Dict[str, str]] = []
    body_fields = set(endpoint["body_fields"])
    upload_fields = set(endpoint["upload_fields"])

    if endpoint["auth_required"]:
        request["auth"] = {
            "type": "bearer",
            "bearer": [{"key": "token", "value": "{{shopToken}}", "type": "string"}],
        }

    if endpoint["needs_file"] or upload_fields:
        if not upload_fields:
            upload_fields.add("file")
        form_data: List[Dict[str, Any]] = []
        for upload_field in sorted(upload_fields):
            form_data.append(
                {"key": upload_field, "type": "file", "src": "", "description": "Attach a local file"}
            )
            body_fields.discard(upload_field)
        for body_field in sorted(body_fields):
            form_data.append(
                {
                    "key": body_field,
                    "value": str(infer_field_example(body_field)),
                    "type": "text",
                }
            )
        request["body"] = {"mode": "formdata", "formdata": form_data}
    elif body_fields:
        payload = {field: infer_field_example(field) for field in sorted(body_fields)}
        headers.append({"key": "Content-Type", "value": "application/json"})
        request["body"] = {
            "mode": "raw",
            "raw": json.dumps(payload, indent=2),
            "options": {"raw": {"language": "json"}},
        }

    if headers:
        request["header"] = headers
    return request


def ensure_folder(parent_items: List[Dict[str, Any]], folder_name: str) -> Dict[str, Any]:
    for item in parent_items:
        if item.get("name") == folder_name and isinstance(item.get("item"), list):
            return item
    new_folder = {"name": folder_name, "item": []}
    parent_items.append(new_folder)
    return new_folder


def build_generated_tree(endpoints: Sequence[Dict[str, Any]], root_name: str) -> Dict[str, Any]:
    root = {"name": root_name, "description": AUTO_GENERATED_TAG, "item": []}
    sorted_endpoints = sorted(
        endpoints, key=lambda entry: (entry["route_file_relative"], entry["path"], entry["method"])
    )
    for endpoint in sorted_endpoints:
        route_parts = Path(endpoint["route_file_relative"]).with_suffix("").parts
        current = root
        for part in route_parts:
            current = ensure_folder(current["item"], part)
        current["item"].append(
            {
                "name": f"{endpoint['method']} {endpoint['path']}",
                "request": build_request(endpoint),
                "response": [],
            }
        )
    return root


def default_collection(collection_name: str) -> Dict[str, Any]:
    return {
        "info": {
            "name": collection_name,
            "schema": POSTMAN_SCHEMA,
        },
        "item": [],
        "variable": [],
    }


def load_collection(path: Path, collection_name: str) -> Dict[str, Any]:
    if not path.exists():
        return default_collection(collection_name)
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"Failed to parse existing collection JSON: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError("Existing collection JSON is not an object.")
    data.setdefault("info", {})
    data.setdefault("item", [])
    data.setdefault("variable", [])
    if "name" not in data["info"]:
        data["info"]["name"] = collection_name
    if "schema" not in data["info"]:
        data["info"]["schema"] = POSTMAN_SCHEMA
    return data


def replace_generated_root(
    collection: Dict[str, Any], generated_root: Dict[str, Any], root_name: str
) -> None:
    items = collection.setdefault("item", [])
    kept: List[Dict[str, Any]] = []
    for item in items:
        if (
            item.get("name") == root_name
            and isinstance(item.get("item"), list)
            and AUTO_GENERATED_TAG in str(item.get("description", ""))
        ):
            continue
        kept.append(item)
    kept.append(generated_root)
    collection["item"] = kept


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate/update Postman collection JSON from Express routes."
    )
    parser.add_argument(
        "--project-root",
        "--backend-root",
        dest="project_root",
        default=".",
        help="Project root directory for path resolution",
    )
    parser.add_argument(
        "--server-file",
        default=None,
        help="Server entry file. When omitted, a best-effort discovery is used.",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Path for the Postman collection JSON. Defaults to ./postman/<project>.postman_collection.json",
    )
    parser.add_argument(
        "--collection-name",
        default=None,
        help="Postman collection name. Defaults to <Project Name> API",
    )
    parser.add_argument("--base-url", default="http://localhost:3000", help="Default baseUrl variable")
    parser.add_argument(
        "--generated-root-name",
        default="source",
        help="Top-level generated folder name inside collection",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str]) -> int:
    args = parse_args(argv)

    project_root = Path(args.project_root).resolve()
    server_file = discover_server_file(project_root, args.server_file)
    output_file = (
        resolve_path_from_root(project_root, args.output)
        if args.output
        else default_output_path(project_root)
    )
    collection_name = args.collection_name or default_collection_name(project_root)

    if not project_root.exists():
        print(f"Error: project root not found: {project_root}", file=sys.stderr)
        return 1
    if not server_file:
        print(
            "Error: unable to discover server file. Pass --server-file explicitly.",
            file=sys.stderr,
        )
        return 1
    if not server_file.exists():
        print(f"Error: server file not found: {server_file}", file=sys.stderr)
        return 1

    server_text = read_text(server_file)
    mounts = extract_mounts(server_file, server_text)
    if not mounts:
        print(
            "Error: no mounted routers discovered from app.use(...) in server file.",
            file=sys.stderr,
        )
        return 1

    requirement_cache: Dict[Path, Dict[str, Any]] = {}
    endpoints: List[Dict[str, Any]] = []
    for mount in mounts:
        route_file = mount["route_file"]
        if not route_file.exists():
            print(f"Warning: route file not found: {route_file}", file=sys.stderr)
            continue
        endpoints.extend(
            parse_route_endpoints(
                route_file=route_file,
                mount_path=mount["mount_path"],
                project_root=project_root,
                requirement_cache=requirement_cache,
            )
        )

    if not endpoints:
        print("Error: no router endpoints discovered.", file=sys.stderr)
        return 1

    collection = load_collection(output_file, collection_name)
    collection["info"]["name"] = collection.get("info", {}).get("name") or collection_name
    collection["info"]["schema"] = POSTMAN_SCHEMA

    ensure_variable(
        collection,
        "baseUrl",
        args.base_url,
        "Base URL for API requests, including protocol and port.",
    )
    ensure_variable(
        collection,
        "shopToken",
        "replace-with-shop-token",
        "Bearer token used by auth middleware.",
    )
    ensure_variable(
        collection,
        "turnstileToken",
        "replace-with-turnstile-token",
        "Turnstile token for human verification when required.",
    )

    generated_root = build_generated_tree(endpoints, args.generated_root_name)
    replace_generated_root(collection, generated_root, args.generated_root_name)

    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(json.dumps(collection, indent=2) + "\n", encoding="utf-8")

    print(f"Synced Postman collection: {output_file}")
    print(f"Discovered endpoints: {len(endpoints)}")
    print(f"Generated root folder: {args.generated_root_name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
